import type { Metadata } from "next";
import React from "react";
import { PrimeReactProvider } from "primereact/api";

import "primeicons/primeicons.css";
import "primeflex/primeflex.css";
import "primereact/resources/themes/lara-light-cyan/theme.css";

import "@/scss/index.scss";

export const metadata: Metadata = {
  title: "Music platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className="text-color">
        <PrimeReactProvider>{children}</PrimeReactProvider>
      </body>
    </html>
  );
}
